"""
modules/download_page.py
------------------------
Premium Download Center - provides multi-format planning sheet exports
(CSV, Excel, Executive PDF Summary), report statistics, and search previews.
"""

import io
import datetime
import pandas as pd
import streamlit as st

from modules.utils import inject_global_css, section_header, kpi_card, fmt_currency, fmt_compact
from modules.pipeline import get_prediction_path, prediction_exists


@st.cache_data
def _convert_df_to_excel(df: pd.DataFrame) -> bytes:
    """Convert dataframe to Excel sheet bytes using openpyxl."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Safety_Stock_Plan')
    return output.getvalue()


@st.cache_data
def _convert_df_to_pdf_summary(df: pd.DataFrame, month_label: str, health_score: float, crit_count: int, user_display: str) -> bytes:
    """Generate a clean plain-text corporate executive summary report bytes."""
    output = io.BytesIO()
    total_cost = df["Order_Cost"].sum() if "Order_Cost" in df.columns else 0
    total_qty  = df["Order_Quantity"].sum() if "Order_Quantity" in df.columns else 0
    
    summary_text = f"""========================================================================
             ENTERPRISE PROCUREMENT PLANNING EXECUTIVE REPORT
========================================================================
Generated on:    {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Planning Cycle:  {month_label}
Generated By:    {user_display}
Organization:    Supply Chain & Operations Division
========================================================================

1. EXECUTIVE PLANNING METRICS
-----------------------------
* Total Material Codes Evaluated:  {len(df):,}
* Total Purchase Orders Required:  {int((df['Order_Quantity'] > 0).sum() if 'Order_Quantity' in df.columns else 0):,}
* Total Recommended Purchase Qty:  {total_qty:,.0f} Units
* Estimated Purchase Budget Allocation: ₹{total_cost:,.2f}

2. SYSTEM HEALTH & RISK INDICATORS
----------------------------------
* Portfolio Inventory Health Score: {health_score:.1f}%
* Active Deficit Critical Materials: {crit_count}
* Understocked Materials:           {int((df['Inventory_Status'] == 'Understock').sum() if 'Inventory_Status' in df.columns else 0):,}
* Overstocked Materials:            {int((df['Inventory_Status'] == 'Overstock').sum() if 'Inventory_Status' in df.columns else 0):,}

3. POLICY RECOMMENDATIONS
-------------------------
- Review all materials in Critical Priority. Place purchasing requisitions immediately.
- Optimize cash positions for Overstocked materials by deferring future order cycles.
- Re-negotiate volume contracts for items showing high purchase cost concentrations.

========================================================================
             END OF EXECUTIVE PROCUREMENT REPORT
========================================================================
"""
    output.write(summary_text.encode('utf-8'))
    return output.getvalue()


def render_download_page() -> None:
    inject_global_css()

    st.markdown("## 📥 Download Planning Reports")
    st.markdown(
        '<p style="color:#8B949E;margin-top:-8px;font-size:14px;">Download finalized demand smoothing forecasts and reorder plans in multiple formats.</p>',
        unsafe_allow_html=True,
    )

    pred_path = get_prediction_path()

    if not prediction_exists():
        st.markdown("""
        <div style="background:rgba(22, 27, 34, 0.45);border:1px dashed rgba(255,255,255,0.08);border-radius:12px;
                    padding:64px 48px;text-align:center;margin-top:24px;backdrop-filter:blur(10px);">
            <div style="font-size:54px;margin-bottom:16px;">📥</div>
            <div style="font-size:22px;font-weight:800;color:#F0F6FC;margin-bottom:10px;">
                No Reports Generated
            </div>
            <div style="font-size:14px;color:#8B949E;max-width:420px;margin:0 auto;line-height:1.5;">
                Ingest transactional sheets and run the smoothing calculations to compile report downloads.
            </div>
        </div>
        """, unsafe_allow_html=True)
        return

    # Load data
    try:
        df = pd.read_csv(pred_path)
    except Exception as e:
        st.error(f"Could not read prediction outputs: {e}")
        return

    # Resolve active headers
    qty_col    = next((c for c in df.columns if "order_quantity" in c.lower()), None)
    cost_col   = next((c for c in df.columns if "order_cost" in c.lower()), None)
    status_col = next((c for c in df.columns if "inventory_status" in c.lower()), None)
    date_col   = next((c for c in df.columns if "forecast_date" in c.lower()), None)

    # Establish metadata
    user_name = st.session_state.get("user_name", "Corporate Manager")
    role      = st.session_state.get("role", "manager")
    
    forecast_month = "Next Cycle"
    if date_col and len(df) > 0:
        try:
            forecast_month = pd.to_datetime(df[date_col].iloc[0]).strftime("%B %Y")
        except Exception:
            forecast_month = str(df[date_col].iloc[0])

    total_materials = len(df)
    materials_order = int((df[qty_col] > 0).sum()) if qty_col else 0
    total_cost      = df[cost_col].sum() if cost_col else 0
    critical_count  = int((df[status_col] == "Critical").sum()) if status_col else 0
    
    health_score    = 100.0
    if total_materials > 0 and status_col:
        health_score = (df[status_col] != "Critical").sum() / total_materials * 100

    # ── Executive Metadata ───────────────────────────────────────────────────
    st.markdown('<div class="divider"></div>', unsafe_allow_html=True)
    
    m1, m2, m3 = st.columns(3)
    with m1:
        st.markdown(f"""
        <div style="background:rgba(22, 27, 34, 0.4); border:1px solid rgba(255,255,255,0.05); border-radius:10px; padding:12px 18px; height:80px;">
            <div style="font-size:11px; color:#8B949E; text-transform:uppercase; font-weight:700;">Target Planning Month</div>
            <div style="font-size:15px; color:#F0F6FC; font-weight:700; margin-top:4px;">📅 {forecast_month}</div>
        </div>
        """, unsafe_allow_html=True)
    with m2:
        st.markdown(f"""
        <div style="background:rgba(22, 27, 34, 0.4); border:1px solid rgba(255,255,255,0.05); border-radius:10px; padding:12px 18px; height:80px;">
            <div style="font-size:11px; color:#8B949E; text-transform:uppercase; font-weight:700;">Compiled On</div>
            <div style="font-size:15px; color:#F0F6FC; font-weight:700; margin-top:4px;">⏱️ {datetime.datetime.now().strftime('%Y-%m-%d')}</div>
        </div>
        """, unsafe_allow_html=True)
    with m3:
        st.markdown(f"""
        <div style="background:rgba(22, 27, 34, 0.4); border:1px solid rgba(255,255,255,0.05); border-radius:10px; padding:12px 18px; height:80px;">
            <div style="font-size:11px; color:#8B949E; text-transform:uppercase; font-weight:700;">Generated By</div>
            <div style="font-size:15px; color:#F0F6FC; font-weight:700; margin-top:4px;">👤 {user_name} ({role.upper()})</div>
        </div>
        """, unsafe_allow_html=True)

    # ── Report Statistics ────────────────────────────────────────────────────
    st.markdown('<br>', unsafe_allow_html=True)
    section_header("Executive Report Summary Metrics")
    
    k1, k2, k3, k4 = st.columns(4)
    with k1: kpi_card("Total Materials",    fmt_compact(total_materials), "📦")
    with k2: kpi_card("Reorder Cost (₹)",   fmt_currency(total_cost),     "💰")
    with k3: kpi_card("Critical Deficits",  str(critical_count),          "🚨",
                       "Immediate order" if critical_count > 0 else "All stocks safe",
                       "#F85149" if critical_count > 0 else "#3FB950")
    with k4: kpi_card("Inventory Health",   f"{health_score:.1f}%",       "❤️",
                       "Sufficient buffers" if health_score > 90 else "Action Required",
                       "#3FB950" if health_score > 90 else "#E3B341")

    # ── Download Cards ───────────────────────────────────────────────────────
    st.markdown('<div class="divider"></div>', unsafe_allow_html=True)
    section_header("Download planning exports")

    d1, d2, d3 = st.columns(3)
    
    with d1:
        st.markdown("""
        <div class="kpi-card" style="padding:22px; text-align:center; height:130px; margin-bottom:12px;">
            <div style="font-size:24px; margin-bottom:4px;">📋</div>
            <div style="font-weight:700; color:#F0F6FC; font-size:13.5px;">Standard CSV File</div>
            <div style="font-size:11px; color:#8B949E; margin-top:2px;">Ideal for import to ERPs (SAP/Oracle).</div>
        </div>
        """, unsafe_allow_html=True)
        csv_bytes = df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Download CSV Report",
            data=csv_bytes,
            file_name=f"Safety_Stock_Plan_{datetime.datetime.now().strftime('%Y%m')}.csv",
            mime="text/csv",
            use_container_width=True,
            type="primary"
        )

    with d2:
        st.markdown("""
        <div class="kpi-card" style="padding:22px; text-align:center; height:130px; margin-bottom:12px;">
            <div style="font-size:24px; margin-bottom:4px;">📊</div>
            <div style="font-weight:700; color:#F0F6FC; font-size:13.5px;">Excel Workbook</div>
            <div style="font-size:11px; color:#8B949E; margin-top:2px;">Includes spreadsheet filters.</div>
        </div>
        """, unsafe_allow_html=True)
        excel_bytes = _convert_df_to_excel(df)
        st.download_button(
            label="📥 Download Excel Workbook",
            data=excel_bytes,
            file_name=f"Safety_Stock_Plan_{datetime.datetime.now().strftime('%Y%m')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
            type="primary"
        )

    with d3:
        st.markdown("""
        <div class="kpi-card" style="padding:22px; text-align:center; height:130px; margin-bottom:12px;">
            <div style="font-size:24px; margin-bottom:4px;">📄</div>
            <div style="font-weight:700; color:#F0F6FC; font-size:13.5px;">Executive Summary (.txt)</div>
            <div style="font-size:11px; color:#8B949E; margin-top:2px;">Print-ready procurement memo.</div>
        </div>
        """, unsafe_allow_html=True)
        pdf_summary_bytes = _convert_df_to_pdf_summary(df, forecast_month, health_score, critical_count, user_name)
        st.download_button(
            label="📥 Download Executive Summary",
            data=pdf_summary_bytes,
            file_name=f"SCM_Executive_Summary_{datetime.datetime.now().strftime('%Y%m')}.txt",
            mime="text/plain",
            use_container_width=True,
            type="primary"
        )

    # ── Report Preview ───────────────────────────────────────────────────────
    st.markdown('<div class="divider"></div>', unsafe_allow_html=True)
    section_header("Audit Ledger Preview")
    st.caption(f"Displaying top 100 rows of {total_materials:,} planning rows. Use filters or headers to audit.")
    
    display_df = df.head(100).copy()
    for col in display_df.columns:
        if display_df[col].dtype in ("float64", "float32"):
            display_df[col] = display_df[col].round(2)
            
    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True,
        height=400
    )
